gcc -Wall -Wvla -Werror -g -std=c11 -fsanitize=address vm_riskxvii.c decode.c virtual_routines.c -o vm_riskxvii


diff --strip-trailing-cr ./tests/arithmetic.out <(./vm_riskxvii < ./vm_riskxvii tests/arithmetic.mi)
diff --strip-trailing-cr ./tests/branch.out <(./vm_riskxvii < ./vm_riskxvii tests/branch.mi)
diff --strip-trailing-cr ./tests/cpu_halt.out <(./vm_riskxvii < ./vm_riskxvii tests/cpu_halt.mi)
diff --strip-trailing-cr ./tests/dump_memory_word.out <(./vm_riskxvii < ./vm_riskxvii tests/dump_memory_word.mi)
diff --strip-trailing-cr ./tests/dump_pc.out <(./vm_riskxvii < ./vm_riskxvii tests/dump_pc.mi)
diff --strip-trailing-cr ./tests/dump_registers.out <(./vm_riskxvii < ./vm_riskxvii tests/dump_registers.mi)
diff --strip-trailing-cr ./tests/free_malloc.out <(./vm_riskxvii < ./vm_riskxvii tests/free_malloc.mi)
diff --strip-trailing-cr ./tests/illegal_free.out <(./vm_riskxvii < ./vm_riskxvii tests/illegal_free.mi)
diff --strip-trailing-cr ./tests/load_blob.out <(./vm_riskxvii < ./vm_riskxvii tests/load_blob.mi)
diff --strip-trailing-cr ./tests/load_illegal.out <(./vm_riskxvii < ./vm_riskxvii tests/load_illegal.mi)
diff --strip-trailing-cr ./tests/load_malloc_illegal.out <(./vm_riskxvii < ./vm_riskxvii tests/load_malloc_illegal.mi)
diff --strip-trailing-cr ./tests/load_malloc.out <(./vm_riskxvii < ./vm_riskxvii tests/load_malloc.mi)
diff --strip-trailing-cr ./tests/request_malloc.out <(./vm_riskxvii < ./vm_riskxvii tests/request_malloc.mi)
diff --strip-trailing-cr ./tests/slt.out <(./vm_riskxvii < ./vm_riskxvii tests/slt.mi)
diff --strip-trailing-cr ./tests/store_data.out <(./vm_riskxvii < ./vm_riskxvii tests/store_data.mi)
diff --strip-trailing-cr ./tests/store_inst_illegal.out <(./vm_riskxvii < ./vm_riskxvii tests/store_inst_illegal.mi)
diff --strip-trailing-cr ./tests/store_malloc_illegal.out <(./vm_riskxvii < ./vm_riskxvii tests/store_malloc_illegal.mi)
diff --strip-trailing-cr ./tests/store_malloc.out <(./vm_riskxvii < ./vm_riskxvii tests/store_malloc.mi)
diff --strip-trailing-cr ./tests/write_character.out <(./vm_riskxvii < ./vm_riskxvii tests/write_character.mi)
diff --strip-trailing-cr ./tests/write_int.out <(./vm_riskxvii < ./vm_riskxvii tests/write_int.mi)
diff --strip-trailing-cr ./tests/write_uint.out <(./vm_riskxvii < ./vm_riskxvii tests/write_uint.mi)
diff --strip-trailing-cr ./tests/not_implemented.out <(./vm_riskxvii < ./vm_riskxvii tests/not_implemented.mi)